<header>
	<h2 class="article_heading">Upload image</h2>
</header>
<section id="upload_form_holder">
	<form id="image_upload_form" action="<?php echo $_SERVER['REQUEST_URI']?>/upload" method="post" enctype="multipart/form-data">
		<?php echo $this->upload_message."\n"; ?>
		<div id="upload_tool">
			<input type="file" id="news_item_image" name="news_item_image" class="browse" />
		    <br /><small id="f_msg"></small>
	    </div>	
		<div id="loader"><img src="<?php echo $this->baseUrl('public/images/ajax-loader.gif')?>" alt="Loading" /></div>
		<p>
		<input type="submit" name="submit" value="Upload" class="custom_btn" />
		</p>
		<br />
	</form>
</section>

<section id="delete_form_holder">
	<form id="image_delete_form">
		<h3>Mange images</h3>
		<div id="delete_message"></div>	
		<div id="browse_tool">
			<?php echo $this->image_list; ?>
		</div>
		<div id="browse_tool_helper">
			<p>
			<input type="text" id="news_item_lib_image" name="news_item_lib_image" class="image_delete_form_data" readonly />
			<div id="loader2"><img src="<?php echo $this->baseUrl('public/images/ajax-loader.gif')?>" alt="Loading" /></div>
			</p>
			<input type="submit" name="submit" value="Delete selected image" class="custom_btn" />
		</div>
	</form>	
</section>

<script src="<?php echo $this->baseUrl('public/js/images_default.js'); ?>" type="text/javascript"></script>