<header>
	<h2>Create a news item</h2>
</header>
<!-- <section> -->
<!-- 	<span id="form_link_1" class="btn_link" data-state="1">Create new item</span> -->
<!-- </section> -->
<section id="news_form_holder">
	<?php include_once 'includes/news_form.php';?>
</section>

<script src="<?php echo $this->baseUrl('public/js/news_default.js'); ?>" type="text/javascript"></script>
<script>
$(function() {
	$("#lib_images").imagepicker();
});
</script> 