<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>RCC - Student Support Services</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/jquery.tablesorter.pager.css'); ?>" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/normalize.min.css'); ?>" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/main.css'); ?>" />
        <script src="<?php echo $this->baseUrl('public/js/jquery.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('public/js/jquery-migrate-1.0.0.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl('public/js/jquery.jqEasyCharCounter.min.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl('public/js/jquery.tablesorter.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl('public/js/jquery.tablesorter.widgets.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl('public/js/jquery.tablesorter.pager.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('public/js/vendor/modernizr-2.6.2.min.js'); ?>" type="text/javascript"></script>                 
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <div class="header-container">
            <header class="wrapper clearfix">
                <h1 class="title"><a href="<?php echo $this->placeholder('home_link') != "" ? $this->placeholder('home_link').'test' : $this->baseUrl();?>"><?php echo $this->placeholder('home_title') !="" ? $this->placeholder('home_title') : "SSS News Push Manager"; ?></a></h1>
                <?php if(isset($_SESSION['auth_session_data'])) { ?>
                <nav>
                    <ul>
                        <li><a <?php if($_SERVER['REQUEST_URI'] == $this->baseUrl()."/news") echo "class=\"selected\" "; ?>href="<?php echo $this->baseUrl(); ?>/news">News</a></li>
                        <li><a <?php if($_SERVER['REQUEST_URI'] == $this->baseUrl()."/images") echo "class=\"selected\" "; ?>href="<?php echo $this->baseUrl(); ?>/images">Images</a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/index/logout/">Log Out</a></li>
                    </ul>
                </nav>
                <?php } ?>
            </header>
        </div>

        <div class="main-container">
            <div class="main wrapper clearfix">
                <article>   	
                	<?php echo $this->layout()->content; ?> 
                </article>				
            </div> <!-- #main -->
        </div> <!-- #main-container -->

        <div class="footer-container">
            <footer class="wrapper">
                <strong>&copy; Riverside City College <?php echo date('Y');?></strong>
            </footer>
        </div>
        
        <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl('public/js/vendor/jquery-1.10.1.min.js'); ?>"><\/script>')</script>        
        <script src="<?php echo $this->baseUrl('public/js/plugins.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('public/js/main.js'); ?>"></script>
        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src='//www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>
